### ISSUE TITLE
Fix raise zombie

### ISSUE THREAD

**Issue by aok17** [jonathanpaulson/minions#27]
Raise zombie should allow a unit to spawn 1 free zombie, following normal spawning rules.

**Comment by jonathanpaulson** [comment]
So just put a zombie in your reinforcements?

**Comment by aok17** [comment]
No, any unit can spawn this zombie as long as it's not newly spawned already.

**Comment by jonathanpaulson** [comment]
Fixed, I think. The only issue was that raise zombie wrongly allowed you to spawn next to a newly spawned unit, right?

**Comment by aok17** [comment]
Correct.
