### ISSUE TITLE
Reinforcements ghosts

### ISSUE THREAD

**Issue by aok17** [jonathanpaulson/minions#29]
It can be difficult to unbuy a unit if you can't remember which one on the board was new and which ones were old. If units bought that turn have a ghost version in your reinforcements, right clicking on it could unplace it and then right clicking again could unbuy it.

**Comment by lightvector** [comment]
To what degree does being able to right click on the unit in the tech line to unbuy it mitigate this issue? Still a little less good due to not giving an obvious visual cue as to what type of unit was bought?

**Comment by aok17** [comment]
Is that something that currently exists? I didn't realize that worked.

**Comment by lightvector** [comment]
Yeah, it currently exists and should work.
