### ISSUE TITLE
Undo lost ability to pick necromancers somehow

### ISSUE THREAD

**Issue by jonathanpaulson** [jonathanpaulson/minions#63]
Can't repro :(

**Comment by jonathanpaulson** [comment]
Also happened to aok

**Comment by aok17** [comment]
Happened Monday to me, and today to Meghal.

**Comment by jonathanpaulson** [comment]
Can the list have duplicates? Probably.

aok couldn't get back to his original necromancer.

**Comment by aok17** [comment]
Neil encountered. Text was:
GAME: Team Red resigned board 3!
ERROR: No actions to undo by this piece this turn
ERROR: No actions to undo by this piece this turn
ERROR: No non-newly-spawned piece with spawn in range

**Comment by jonathanpaulson** [comment]
Happened after winning on mana spires. Kept PickingNecromancer ability but clicking didn't do anything.

**Comment by jonathanpaulson** [comment]
This is fixed
