### ISSUE TITLE
2020 Techline Update

### ISSUE THREAD

**Issue by goldenratio1618** [jonathanpaulson/minions#75]
- Dark Towers should now be $3/3, deadly/1, s1r1, swarm, spawn, lumbering
- Vampires should now be $5/2, 3/10, s1r1, persistent
- Mummies should now be $6/2, 5/13, s1r1, flurry, spawn
- Liches should now be $7/3, deadly/3, s1r3, lumbering
- Spires no longer exist
- Mana Necromancer no longer exists

**Comment by jonathanpaulson** [comment]
Done. I took the liberty of renaming "Dark Tower" to "Ooze"
