### ISSUE TITLE
Add UI for board reset - choose new necromancer

### ISSUE THREAD

**Issue by jonathanpaulson** [jonathanpaulson/minions#8]
Choosing advanced captain
Choosing unit to keep

Are these choices made simultaneously? I guess at the start of each team's turn? That means we need an "unknown Necromancer" placeholder for the first turn of a new board

**Comment by aok17** [comment]
Quick fix that could be done to auto-choose saved unit:
1. Most expensive
2. Spawner
3. Most advanced tech unit

**Comment by lightvector** [comment]
Half of this is handled with https://github.com/jonathanpaulson/minions/pull/38

**Comment by jonathanpaulson** [comment]
This is now done
